name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [src/main.cpp]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      # - name: Download external library
      #   run: |
      #     wget https://github.com/xxxajk/spi4teensy3/archive/master.zip -O /tmp/spi4teensy3.zip
      #     unzip /tmp/spi4teensy3.zip -d /tmp

      - name: Run PlatformIO
        run: pio ci --lib="." --board=lilygo-t-display
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
      
      - name: Combine Binaries
        run: esptool.py --chip esp32 merge_bin -o .pio/build/ttgoDisplay/webflash.bin --flash_mode dio --flash_size 4MB 0x1000 .pio/build/ttgoDisplay/bootloader.bin 0x8000 .pio/build/ttgoDisplay/partitions.bin 0x10000 .pio/build/ttgoDisplay/firmware.bin

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          path: .pio/build/ttgoDisplay/
          name: firmware.bin
          retention-days: 120
          overwrite: true