<!doctype html>
<html lang="de">

<head>
    <!-- Meta's -->
    <?= $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        //->appendHttpEquiv('content-type', 'text/html;charset=UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no, initial-scale=1.0')
        ->appendName('author', 'Michael Krasselt')
        ->appendName('description', 'A tool to check worker tickets when entering their bus to work and bill the tours made to the company')
        . "\n";
    ?>
    <meta charset="utf-8">
    <meta name="theme-color" content="#712cf9">
    <link rel="icon" href="<?= $this->basePath('img/favicon.ico'); ?>">

    <?= $this->headTitle("Bus Rider")->setAutoEscape(false) . "\n"; ?>

    <!-- Bootstrap core CSS -->
    <link href="<?= $this->basePath('css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= $this->basePath('css/dashboard.css'); ?>" rel="stylesheet">

    <!-- Style -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/favicon.png')))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-icons.min.css'))
        ->prependStylesheet($this->basePath('css/dashboard.css'))
        . "\n";
    echo $this->headScript()

        ->prependFile($this->basePath('js/color-modes.js'), 'text/javascript')
        ->prependFile($this->basePath("js/dashboard.js"), 'text/javascript')
        // ->prependFile($this->basePath('js/main.js'), 'text/javascript')
        // ->prependFile($this->basePath('js/npm.js'), 'text/javascript')
        ->prependFile('https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js', 'text/javascript')
        ->prependFile($this->basePath('js/bootstrap.bundle.js'), 'text/javascript')
        ->prependFile($this->basePath('js/jquery-3.7.1.min.js'), 'text/javascript')
        . "\n";
    ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="<?= $this->url("home") ?>">
            <?= $this->translate('Bus-Rider') ?>
            <!-- place logo here like this <img src="<?= $this->basePath("img/logo.png") ?>">-->
        </a>
        <ul class="navbar-nav flex-row d-md-none">
            <li class="nav-item text-nowrap">
                <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle search">
                    <i class="bi-search"></i>
                </button>
            </li>
            <li class="nav-item text-nowrap">
                <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="bi-list"></i>
                </button>
            </li>
        </ul>

        <div id="navbarSearch" class="navbar-search w-100 collapse">
            <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
        </div>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
                <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
                        <ul class="nav flex-column" style="user-select: none;">
                            <?php
                            if (isset($activeMenuItemId)) {
                                $this->mainMenu()->setActiveItemId($activeMenuItemId);
                            }
                            // Render the navbar 
                            //TODO hide for now
                            // echo $this->mainMenu()->render("login");
                            ?>
                        </ul>

                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                            <span><?= $this->translate('readers') ?></span>
                            <a class="link-secondary" href="<?= $this->url("reader", ["action" => "add"]) ?>" aria-label="<?= $this->translate('addReader') ?>">
                                <i class="bi bi-person-badge"></i><i class="bi-plus-circle"></i>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="<?= $this->url("reader") ?>">
                                    <i class="bi bi-person-badge"></i>
                                    <i class="bi bi-card-list"></i>
                                    <?= $this->translate('reader list') ?>
                                </a>
                            </li>
                        </ul>
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                            <span><?= $this->translate('cards') ?></span>
                            <a class="link-secondary" href="<?= $this->url("rider/card", ["action" => "add"]) ?>" aria-label="<?= $this->translate('addCard') ?>">
                                <i class="bi bi-person-badge"></i><i class="bi-plus-circle"></i>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="<?= $this->url("rider/card") ?>">
                                    <i class="bi bi-person-badge"></i>
                                    <i class="bi bi-card-list"></i>
                                    <?= $this->translate('card list') ?>
                                </a>
                            </li>
                        </ul>
                        <hr class="my-3">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                            <span><?= $this->translate('companies') ?></span>
                            <a class="link-secondary" href="<?= $this->url("company", ["action" => "add"]) ?>" aria-label="<?= $this->translate('addCompany') ?>">
                                <i class="bi bi-building"></i><i class="bi-plus-circle"></i>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="<?= $this->url("company") ?>">
                                    <i class="bi bi-building"></i>
                                    <i class="bi bi-card-list"></i>
                                    <?= $this->translate('company list') ?>
                                </a>
                            </li>
                            <?= $this->CompanyMenu(
                                <<<TEMPLATE
                                <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="{{URL}}">
                                    {{NAME}}
                                </a>
                            </li>
                            TEMPLATE,
                                $this->url("company", ["action" => "details", "id" => "ID"])
                            ); ?>
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="<?= $this->url("rider") ?>">
                                    <i class="bi bi-person-arms-up"></i>
                                    <i class="bi bi-card-list"></i>
                                    <?= $this->translate('complete rider list') ?>
                                </a>
                            </li>
                        </ul>
                        <hr class="my-3">
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                            <span><?= $this->translate('routes') ?></span>
                            <a class="link-secondary" href="<?= $this->url("routes", ["action" => "add"]) ?>" aria-label="<?= $this->translate('addRoute') ?>">
                                <i class="bi bi-signpost-split"></i><i class="bi-plus-circle"></i>
                            </a>
                        </h6>
                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="<?= $this->url("routes") ?>">
                                    <i class="bi bi-signpost-split"></i><i class="bi bi-card-list"></i>
                                    <?= $this->translate('routes list') ?>
                                </a>
                            </li>
                        </ul>
                        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                            <span><?= $this->translate('rides') ?></span>
                        </h6>
                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="<?= $this->url("rider/rides") ?>">
                                    <i class="bi bi-ticket-perforated-fill"></i><i class="bi bi-card-list"></i>
                                    <?= $this->translate('rides list') ?>
                                </a>
                            </li>
                            <?= $this->CompanyMenu(
                                <<<TEMPLATE
                                <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="{{URL}}">
                                    {{NAME}}
                                </a>
                            </li>
                            TEMPLATE,
                                $this->url("rider/rides", ["action" => "company", "id" => "ID"])
                            ); ?>
                        </ul>
                        <hr class="my-3">
                        <ul class="nav flex-column mb-auto">
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="#">
                                    <i class="bi-gear-wide-connected"> </i>
                                    <?= $this->translate('settings') ?>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link d-flex align-items-center gap-2" href="#">
                                    <i class="bi-door-closed"></i>
                                    <?= $this->translate('sign out') ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <!--<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2"><?= $this->translate('Dashboard') ?></h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary"><?= $this->translate('Share') ?></button>
                            <button type="button" class="btn btn-sm btn-outline-secondary"><?= $this->translate('Export') ?></button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
                            <i class="bi-calendar3"></i>
                            <?= $this->translate('this week') ?>
                        </button>
                    </div>
                </div>-->
                <!-- End sliders -->
                <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
                <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
                <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>
                <?= $this->content . "\n"; ?>
            </main>
        </div>
    </div>
</body>

</html>