<?php
$this->headTitle($title = 'delete a reader')->setSeparator(" on ");
$form->prepare();
?>
<h1><?= $title ?></h1>
<?= $this->form()->openTag($form); ?>
<div class="table-resp">
    <p>do you really want to delete the reader? it will no longer work</p>
    <?= count($form->getMessages()) ? $this->FormErrorMessage(var_export($form->getMessages(), true)) : ""; ?>
    <div class="form-group">
        <?= $this->formElement($form->get('id')); ?>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->FormErrorMessage($this->formElementErrors($form->get('submit'))); ?>
    </div>
    <?= $this->form()->closeTag($form); ?>
</div>