<?php
return [
    // 'Laminas\Log',
    'Laminas\Cache',
    'Laminas\Cache\Storage\Adapter\Memory',
    'Laminas\Cache\Storage\Adapter\Filesystem',
    'Laminas\Paginator',
    // 'Laminas\Mail',
    // 'Laminas\Mvc\Plugin\FilePrg',
    'Laminas\Mvc\Plugin\FlashMessenger',
    // 'Laminas\Mvc\Plugin\Identity',
    // 'Laminas\Mvc\Plugin\Prg',
    'Laminas\Session',
    // 'Laminas\I18n',
    'Laminas\Form',
    'Laminas\InputFilter',
    'Laminas\Filter',
    'Laminas\Hydrator',
    'Laminas\Router',
    'Laminas\Validator',
    //'Laminas\I18n',
    'Laminas\InputFilter',
    'Laminas\Filter',
    'Laminas\Hydrator',
    'Laminas\Session',
    'Laminas\Diactoros',
    'DoctrineModule',
    'DoctrineORMModule',
    // 'User',
    'Site',
    'Rider',
    'Reader',
];
