<?php

use Rider\Entity\Company;

$this->headTitle($title = 'lists all companies')->setSeparator(" for ");
?>
<h1>
    <?= $title ?>
    <a class="btn btn-primary" href="<?= $this->url("company", ["action" => "add"]) ?>">
        <i class="bi bi-building-add"></i></a>
</h1>
<div class="table-resp">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>name</th>
                <th>status</th>
                <th>date created</th>
                <th>date modified</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
            <?php

            if (isset($companies) && is_array($companies)) {
                /**
                 * @var Company $company
                 */
                foreach ($companies as $company) {
            ?>
                    <tr>
                        <td><?= $company->getName(); ?></td>
                        <td><?= $company->getStatusAsString(); ?></td>
                        <td><?= $company->getDateCreated()->format("H:i:s d.m.Y") ?></td>
                        <td><?= $company->getDateModified()->format("H:i:s d.m.Y") ?></td>
                        <td>
                            <a class="btn btn-primary" href="<?= $this->url("company", ["action" => "edit", "id" => $company->getId()]) ?>">
                                <i class="bi bi-pencil-square"></i> edit</a>
                            <a class="btn btn-primary" href="<?= $this->url("company", ["action" => "delete", "id" => $company->getId()]) ?>">
                                <i class="bi bi-trash"></i>delete</a>
                        </td>
                    </tr>
            <?php }
            }
            ?>
        </tbody>
    </table>
</div>