<?php
$this->headTitle($title = 'edit the card')->setSeparator(" for ");
$form->prepare();
$cardFieldset = $form->get("card");
?>
<h1><?= $title ?></h1>
<?= $this->form()->openTag($form); ?>
<div class="table-resp">
    <table class="table table-striped">
        <tbody>
            <tr>
                <th><?= $this->formLabel($cardFieldset->get('name')); ?></th>
                <td>
                    <div class="form-group">
                        <?= $this->formElement($cardFieldset->get('name')); ?>
                        <?= $this->FormErrorMessage($this->formElementErrors($cardFieldset->get('name'))); ?>
                    </div>

                </td>
            </tr>
            <tr>
                <th><?= $this->formLabel($cardFieldset->get('status')); ?></th>
                <td>
                    <div class="form-group">
                        <?= $this->formElement($cardFieldset->get('status')); ?>
                        <?= $this->FormErrorMessage($this->formElementErrors($cardFieldset->get('status'))); ?>
                    </div>

                </td>
            </tr>
        </tbody>
    </table>
    <?= count($form->getMessages()) ? $this->FormErrorMessage(var_export($form->getMessages(), true)) : ""; ?>
    <div class="form-group">
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->FormErrorMessage($this->formElementErrors($form->get('submit'))); ?>
    </div>
    <?= $this->form()->closeTag($form); ?>
</div>